version: 2.4.2.{build}
init:
- dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
configuration: Release
before_build:
- cd src
- nuget restore
- cd ..
build:
  verbosity: minimal
  project: ./src/Attest.sln
test_script:
- cd ./devops/test
- test-all.bat
- cd ../..
after_test:
- cd devops
- cd pack
- pack-all
image: Visual Studio 2019
notifications:
- provider: Email
  to:
  - godrose@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
artifacts:
- name: Packages
  path: ./output/*.nupkg
- name: Moq Support Living Documentation
  path: ./output/Attest.Fake.Moq.Specs.LivingDoc.html
- name: Setup Living Documentation
  path: ./output/Attest.Fake.Setup.Specs.LivingDoc.html
- name: Core Living Documentation
  path: ./output/Attest.Testing.Core.Specs.LivingDoc.html
- name: SpecFlow Living Documentation
  path: ./output/Attest.Testing.SpecFlow.Specs.LivingDoc.html
...
