version: 2.1.1.{build}
init:
- dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
configuration: Release
before_build:
- nuget restore
build:
  verbosity: minimal
  project: Attest.sln
test_script:
- cd
- cd .\devops\test
- test-all.bat
- cd ..\..\
after_test:
- cd devops
- cd pack
- pack-all
image: Visual Studio 2019
notifications:
- provider: Email
  to:
  - godrose@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
artifacts:
- name: Packages
  path: .\output\*.nupkg
- name: Moq Support Living Documentation
  path: .\Attest.Fake.Moq.Specs\bin\Release\LivingDoc.html
- name: Setup Living Documentation
  path: .\Attest.Fake.Setup.Specs\bin\Release\LivingDoc.html
- name: Core Living Documentation
  path: .\Attest.Testing.Core.Specs\bin\Release\LivingDoc.html
...
